version: "3.4"

services:
  main:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: dev
    image: videoteka_frontend/latest
    ports:
      - "8080:8080"
    volumes:
      - .:/src
    networks:
      - system

networks:
  system:
