version: "3.4"

services:
  main:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: dev
    ports:
      - "8032:8032"
    volumes:
      - .:/src
    networks:
      - system

networks:
  system:
